### ISSUE TITLE
[PE-D][Tester D] add not working with "d/tdy 10am - 2pm"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T10-2/tp#134]
nothing happens when I use the following command
add n/name p/901 d/tdy 10am - 2pm
![Screenshot 2024-04-05 at 16.28.09.png](https://raw.githubusercontent.com/erv-teo/ped/main/files/1825f731-3849-4dee-8ca6-c7b16b3c497b.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: erv-teo/ped#4

**Comment by chengjunyuan** [comment]
Duplicate of #186
