### ISSUE TITLE
[PE-D][Tester C] Ambiguous boundary for the date parameter in the scheduling of appointments

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-2/tp#138]
For the `addappt` command, the boundary of an invalid date seems to be rather inconsistent. I am able to add appointments for dates before the current date.

![image.png](https://raw.githubusercontent.com/casaarlai/ped/main/files/32d7b07c-9911-4ba4-83ba-db46ecc279a4.png)

However I am not able to do so for dates that begin before the year 2000. Perhaps there is some context I am missing here, but from the user guide and program itself, it seems inconsistent to me that dates prior to the current date are valid but only until the year 2000.

![image.png](https://raw.githubusercontent.com/casaarlai/ped/main/files/a4a9d3bd-c8ad-48ed-95b3-f0dc607fa5b2.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: casaarlai/ped#3

**Comment by qinboan** [comment]
@chengjunyuan did you block dates before 2000?

**Comment by minreiseah** [comment]
> Will update the parser to allow extremely old appointments to be registered too.

Perhaps you should just allow appointments from 1819 onward when Sir Stamford Raffles set foot in Singapore and introduced the wonders of western healthcare to our country.

**Comment by minreiseah** [comment]
Resolved by #209
