### ISSUE TITLE
[PE-D][Tester D] Appointment timings are able to overlap

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-2/tp#141]
![Screenshot 2024-04-05 at 16.37.02.png](https://raw.githubusercontent.com/erv-teo/ped/main/files/36647f99-0894-46aa-a129-d6cf16c09afc.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: erv-teo/ped#7

**Comment by minreiseah** [comment]
This is the intended behavior. A clinic can have multiple rooms.
