### ISSUE TITLE
[PE-D][Tester A] Link provided in Help window directs to AB3 guide instead of RapidTracer guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T10-2/tp#157]
**Steps to reproduce:**
1) Run the `help` command

**Expected:**
A help window appears with a link to the user guide of RapidTracer.

**Actual:**
A help window appears with a link to the user guide of AB3.

**Improvement suggestion:**
Update the link to direct to the correct user guide.

**Screenshot:**
![image.png](https://raw.githubusercontent.com/JonChong98/ped/main/files/79c14460-bdfc-4335-8dba-f2d996fc26f6.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: JonChong98/ped#3

**Comment by legionlegion** [comment]
closed by #167

**Comment by legionlegion** [comment]
closed by #167
