### ISSUE TITLE
[PE-D][Tester E] Help window does not re-pop upon minimising

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T10-2/tp#161]
Step to reproduce:
1. type `help`
2. minimise `help` window
3. type `help` again
4. Nothing pop up (expected the help window to re-pop up)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: vnnamng/ped#13

**Comment by minreiseah** [comment]
@legionlegion Do look into this.
