### ISSUE TITLE
[PE-D][Tester B] Date format allowing dates that have already past

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-2/tp#174]
- Readers/Users are able to schedule appointments on dates that have already past and thus defeats the purpose of scheduling. Ideally, I believe the date field should only accept dates in the future.

![date format improved.png](https://raw.githubusercontent.com/Zack-Tay/ped/main/files/2a1ee5a6-b3f2-4dfc-b0cd-52c872e4ad09.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Zack-Tay/ped#12

**Comment by minreiseah** [comment]
This is the intended behavior. In the event of systems migrations, or if the user simply forgot to input a appointment from the day before, they should still be able to key in such appointments.
