### ISSUE TITLE
[PE-D][Tester A] Add command parameters shown in error message differ from User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-2/tp#181]
**Steps to reproduce:**
1) Run `add` to get the error message to appear.

**Expected:**
Add command parameters shown in error message match that found in the user guide.

**Actual:**
Add command parameters shown in the error message show address as a mandatory parameter (without '[ ]').

**Improvement suggestion:**
Update the parameters to match the user guide.

**Screenshot:**
![image.png](https://raw.githubusercontent.com/JonChong98/ped/main/files/486ccbca-1e96-4653-beda-26a759b33077.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: JonChong98/ped#7

**Comment by SampsonYe1999** [comment]
Updated UG according to suggestion.
