### ISSUE TITLE
Overlapping appointment creation allowed

### ISSUE THREAD

**Issue by legionlegion** [AY2324S2-CS2103T-T10-2/tp#213]
**Replicate the behaviour:**
`addappt 2 d/tdy 10am-12pm`
`addappt 2 d/tdy 9am-12pm`

**Result:**
![image](https://github.com/AY2324S2-CS2103T-T10-2/tp/assets/45446291/38f8ca2d-f541-4c44-ba6e-c26a38ffe728)

**Comment by chengjunyuan** [comment]
This is #180 , which Min Rei labelled as Not Allowed to Fix. @minreiseah can check?

**Comment by legionlegion** [comment]
Ah so #180 is for different persons' appointments, this is for a single person, which I thought overlap shouldn't be allowed
