### ISSUE TITLE
Add `date`, `start`, and `end` fields to adding contacts

### ISSUE THREAD

**Issue by chengjunyuan** [AY2324S2-CS2103T-T10-2/tp#30]
There are three new optional fields when adding contacts as per the [v1.2 Feature List](https://docs.google.com/document/d/1f6KBnHuFYMNZQQLIsuGf148wf24TZawrTlgu5dedt2Q/edit), we will add placeholders for these fields first (i.e., the contact will store these fields, but they cannot be used at the moment. Functionality for these fields will be implemented in a later issue)

**Comment by minreiseah** [comment]
If given fields are provided, **both** `Contact` and `Appointment` classes are created.
