### ISSUE TITLE
Add `tags` field to contacts

### ISSUE THREAD

**Issue by chengjunyuan** [AY2324S2-CS2103T-T10-2/tp#32]
As per our [user stories](https://github.com/AY2324S2-CS2103T-T10-2/tp/blob/master/docs/DeveloperGuide.md), add a `tags` field to contacts so that our clerks can tag patients who may have infectious diseases, e.g., Mr Tan is currently COVID-positive. When creating a new contact, this will be an optional field.

**Comment by minreiseah** [comment]
Are spaces allowed in tags? If so, then how will `\t tag 1 tag 2` be parsed? Parsing tags by spaces will be easier.

**Comment by chengjunyuan** [comment]
I realize this is an existing feature in AB3, will take a closer look at it in the future. Under the current implementation in [AB3](https://se-education.org/addressbook-level3/UserGuide.html), it seems that multiple tags are added as `t/tag1 t/tag2`, I don't think spaces are allowed.

**Comment by legionlegion** [comment]
> I realize this is an existing feature in AB3, will take a closer look at it in the future. Under the current implementation in [AB3](https://se-education.org/addressbook-level3/UserGuide.html), it seems that multiple tags are added as `t/tag1 t/tag2`, I don't think spaces are allowed.

Yep, I feel like we can skip this enhancement and prioritise other features, 1 word tags should be enough?

**Comment by minreiseah** [comment]
Closed as current tags are fine.
