### ISSUE TITLE
Add `id`, `startDateTime`, `endDateTime` fields to adding appointment 

### ISSUE THREAD

**Issue by SampsonYe1999** [AY2324S2-CS2103T-T10-2/tp#33]
A new Appointment class is added and there are three fields when creating an appointment as per the [v1.2 Feature List]. These fields will be used for appointment booking and contact tracing which would be implemented in a later version.

**Comment by minreiseah** [comment]
Note that this is blocked by feature #36 which involves creating the data model first.

**Comment by qinboan** [comment]
@SampsonYe1999 is this the same as #43

**Comment by SampsonYe1999** [comment]
> @SampsonYe1999 is this the same as #43

This issue should be a duplicate case of issue #35 and #38. Can be closed.

**Comment by SampsonYe1999** [comment]
Issue closed as it's duplicate case of #35 and #38
