### ISSUE TITLE
Update storage to store contacts and appointments seperately

### ISSUE THREAD

**Issue by qinboan** [AY2324S2-CS2103T-T10-2/tp#34]
We might need to store contacts and appointments in 2 different files to make it easier to work with.

**Comment by minreiseah** [comment]
Blocked by #36

**Comment by minreiseah** [comment]
Note that for testing, we need to load the files into memory. This requires `Person` and `Appointment` constructors that take in `personId: UUID` and `appointmentId: UUID`.

**Comment by minreiseah** [comment]
@qinboan Updated the model in PR #61, but the storage was not fully updated.
