### ISSUE TITLE
Add `startDateTime` and `endDateTime` fields to appointments

### ISSUE THREAD

**Issue by SampsonYe1999** [AY2324S2-CS2103T-T10-2/tp#38]
As per our [user stories](https://github.com/AY2324S2-CS2103T-T10-2/tp/blob/master/docs/DeveloperGuide.md), add a startDateTime and endDateTime fields to appointment so that each appointment will start and end at a specific timing. eg., Mr Tan will be visiting the clinic again for a check up on 2024-04-15 and the clerk assigns him a new appointment on 2024-04-15 10:00 to 2024-04-15 10:30.

**Comment by qinboan** [comment]
blocked by #36
