### ISSUE TITLE
Identify close contacts from an affected appointment

### ISSUE THREAD

**Issue by qinboan** [AY2324S2-CS2103T-T10-2/tp#44]

**Comment by minreiseah** [comment]
![image](https://github.com/AY2324S2-CS2103T-T10-2/tp/assets/58839570/1abb6edd-5bde-47bd-9d93-2b5cb9fa44c6)

**Comment by minreiseah** [comment]
Flow:
![image](https://github.com/AY2324S2-CS2103T-T10-2/tp/assets/58839570/b070e249-13e9-42b6-96a5-59947eb38e58)
