### ISSUE TITLE
Add `findappt` command 

### ISSUE THREAD

**Issue by SampsonYe1999** [AY2324S2-CS2103T-T10-2/tp#47]
As per our [user stories](https://github.com/AY2324S2-CS2103T-T10-2/tp/blob/master/docs/DeveloperGuide.md), add a `find appt` command.

Shows a list of appointments in RapidTracer matching the keywords provided. Found searches must match ALL keywords.
Format: “find appt KEYWORD [MORE_KEYWORDS]”
The KEYWORD searched is case-insensitive.
Order of keywords does not matter.
Possible keyword types: 
NAME, PHONE_NUMBER, ADDRESS, TAG, DATE, START_DATE, END_DATE, (DATE START_TIME, END_TIME to be implemented in a later version) 

E.g. If the clerk wants to find all the appointments booked by a patient called "Sampson", the clerk can use "find appt Sampson" to list out all the appointments booked by Sampson.

**Comment by qinboan** [comment]
blocked by #36

**Comment by minreiseah** [comment]
blocked by #58

**Comment by minreiseah** [comment]
Involves `Model.java#updateFilteredAppointmentList` on top of writing the `FindAppointmentCommand` and `FindApptointmentCommandParser`.
