### ISSUE TITLE
Define project roles & responsibilities

### ISSUE THREAD

**Issue by minreiseah** [AY2324S2-CS2103T-T10-2/tp#48]
Note:
- Team leads are rotated each week
- Track individual contributions under our `johndoe.md` pages
- Note changes under the [project notes](https://docs.google.com/document/d/1VQN1ygdftbojhfbXpzR1gX8I72JL16GP9gYMq72eFPU/edit)

Possible roles:
- Team lead: Responsible for overall project coordination.
- Documentation (short for ‘in charge of documentation’): Responsible for the quality of various project documents.
- Testing: Ensures the testing of the project is done properly and on time.
- Code quality: Looks after code quality, ensures adherence to coding standards, etc.
- Deliverables and deadlines: Ensure project deliverables are done on time and in the right format.
- Integration: In charge of versioning of the code, maintaining the code repository, integrating various parts of the software to create a whole.
- Scheduling and tracking: In charge of defining, assigning, and tracking project tasks.
- [Tool ABC] expert: e.g. IntelliJ expert, Git expert, etc. Helps other team member with matters related to the specific tool.
- In charge of [Component XYZ]: e.g. In charge of Model, UI, Storage, etc. Note that being in charge of a component doesn't mean you are the only one who should be modifying that component. Rather, you are the one who's expected to, know that component best, review changes done to that component in v1.3-v1.4, act as the gate keeper of its quality, help others when they face difficulties while modifying that component etc.

**Comment by chengjunyuan** [comment]
Do we still need this issue? I think we can resolve it, or at least shift it to v1.4 @minreiseah
