### ISSUE TITLE
Add `editappt` command 

### ISSUE THREAD

**Issue by SampsonYe1999** [AY2324S2-CS2103T-T10-2/tp#49]
As per our [user stories](https://github.com/AY2324S2-CS2103T-T10-2/tp/blob/master/docs/DeveloperGuide.md), add an `edit appt` command to edit appointment details.

Format: edit appt INDEX [s/START_TIME] [e/END_TIME]
Edits the appointment at the specified INDEX
INDEX is a positive integer that is currently displayed on the screen.
Only one INDEX can be edited at a time.
At least one of the optional fields must be provided.
Existing values will be updated to the input values.

E.g. If the clinic clerk wants to edit the starting time and end time of an appointment of the fourth contact to “25/02/2024 (13:00)” and “25/02/2024 (14:00)”, he can input "edit appt 4 s/25/02/2024 (13:00) e/25/02/2024 (14:00)”.

**Comment by qinboan** [comment]
blocked by #36
