### ISSUE TITLE
Update README page

### ISSUE THREAD

**Issue by legionlegion** [AY2324S2-CS2103T-T10-2/tp#6]
## UI Mockup

- Add a UI mockup of your intended final product. Note that the image of the UI should be `docs/images/Ui.png` so that it can be downloaded by our scripts.
- Limit the file to contain one screenshot/mockup only and ensure the new image is roughly the same height x width proportions as the original one. Reason: when we compile these images from all teams into one page ([example](#)), yours should not look out of place.
- The UI mockup can be a hand-drawn sketch or created using a tool such as PowerPoint, PlantUML, Figma, etc.
- Can the AB3 screenshot be used for this? Only in the unlikely case that your v1.2 UI looks exactly the same as AB3.

## Project Content Updates

- Update all contents to match your own project.

## Build Status Badge

- Update the link of the GitHub Actions build status badge (Build Status) so that it reflects the build status of your team repo.

## Acknowledgements

- Acknowledge the original source of the code e.g.,
  - This project is based on the AddressBook-Level3 project created by the [SE-EDU initiative](https://se-education.org).

## Also update site-wide settings, as necessary:

You need to update the AB-3 in the top navigation bar of your project website (it's in `docs\_markbind\layouts\default.md` if using MarkBind).

**Comment by minreiseah** [comment]
![Appointment View](https://github.com/AY2324S2-CS2103T-T10-2/tp/assets/58839570/e03d7d5a-5a55-44c9-a433-bbdedc22042a)

Do download this and save as Ui.png
