### ISSUE TITLE
Allow navigation from a `Person` to their list of `Appointments`

### ISSUE THREAD

**Issue by chengjunyuan** [AY2324S2-CS2103T-T10-2/tp#60]
As per our [user stories](https://github.com/AY2324S2-CS2103T-T10-2/tp/blob/master/docs/DeveloperGuide.md), add a new function to allow our clerk to display all the `Appointment`s that a `Contact` has. (Note: `Contact` and `Person` will be used interchangeably because we've yet to refactor the `Person` from AB3 to `Contact` in RT)

Intended usage: given a currently displayed list of `Contact` details, the user (Mr Surya) can type `ga 1` to view all the `Appointment` instances associated with the `Contact` with index 1 currently displayed (fun fact: `ga` is short for "go to appointments").

**Intended Input**: `ga INDEX`

**MSS**
1. Actor searches for appointments related to a specific contact.
2. System displays the appointments related to that specific contact.
Use case ends.

**Extensions**
1a. The given index is invalid.
1a1. System displays an error message.
Use case resumes at step 1.

2a. The list is empty.
Use case ends.

**Comment by minreiseah** [comment]
Blocked by #52

**Comment by minreiseah** [comment]
Partially resolved by #107
