### ISSUE TITLE
Graph view for contact tracing

### ISSUE THREAD

**Issue by minreiseah** [AY2324S2-CS2103T-T10-2/tp#84]
![image](https://github.com/AY2324S2-CS2103T-T10-2/tp/assets/58839570/84985653-9357-43af-9de1-83a3a4179a1b)
Could implement a graph view with n-degrees of contact tracing. Would look something like the above (though much simpler).

**Comment by chengjunyuan** [comment]
Good to add some user stories to add some functionality and contextualize this feature. But looks very cool!

**Comment by minreiseah** [comment]
This is not happening.
