### ISSUE TITLE
Prefix arguments should allow whitespace

### ISSUE THREAD

**Issue by minreiseah** [AY2324S2-CS2103T-T10-2/tp#85]
Current: `n/ John' is an invalid prefix.

Proposed: `n/ John` should be a valid prefix. To implement this, just do a left and right strip on the parsed argument (after the prefix). e.g. `    John     ` --(strip)--> `John`.

**Comment by chengjunyuan** [comment]
I was testing this and it doesn't seem to be an issue, I think someone else added the stripping feature already without closing this 👍 . If anyone can bother finding this, can close this issue.

**Comment by minreiseah** [comment]
It has been resolved by someone.

![image](https://github.com/AY2324S2-CS2103T-T10-2/tp/assets/58839570/3a1cb3ce-fb34-4b31-8985-d75fb93a9cc0)
